#!/usr/bin/env python

import sys

pkg = 'hector_generic_rqt_widgets'
widget = 'gazebo_interface_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))
